## Makefile
## 
##    2014-04-28 - [9527] Create
##
##


.PHONY: all clean

all:
	echo -ne "\n\n\n\n"; cd lib;		        make && cd ..;
	echo -ne "\n\n\n\n"; cd src/cgi;            make && cd ..;make;

clean:
	echo -ne "\n\n\n\n"; cd lib;		        make clean && cd ..;
	echo -ne "\n\n\n\n"; cd src/cgi;            make clean && cd ..;make clean;
